const INCREMENT_LOADING = 'INCREMENT_LOADING';
const INCREMENT_SUCCESS = 'INCREMENT_SUCCESS';
const INCREMENT_ERROR = 'INCREMENT_ERROR';

export {INCREMENT_LOADING, INCREMENT_SUCCESS, INCREMENT_ERROR};
