const USER_DETAILS_LOADING = 'USER_DETAILS_LOADING';
const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';

export {USER_DETAILS_LOADING, USER_DETAILS_SUCCESS, USER_DETAILS_ERROR};
